### ISSUE TITLE
Can not convergence to my mouse dataset

### ISSUE THREAD

**Issue by STAR-811** [neuroethology/BKinD#4]
Hi! That's great work! But it doesn't work on my video. After 100 epochs, the images in the sample folder and my parameter config file are shown below. I try to use the pre-train model to finetune but it doesn't work either. What can I do to improve the keypoint discovery performance on my dataset? (train file contains 40,000 images)

dataset: custom_dataset
data: data/mice
workers: 4
epochs: 300
start_epoch: 0
schedule: 30
batch_size: 16
lr: 0.001
momentum: 0.9
weight_decay: 0.0001
print_freq: 10
pretrained: False
gpu: 0
val_schedule: 20
curriculum: 4

checkpoint: checkpoint/custom_dataset

nkpts: 15

image_size: 256
frame_gap: 15
bounding_box: False  # Only False allowed for the custom dataset

perc_weight: [100.0, 1.6, 2.3, 1.8, 2.8, 100.0]

resume: checkpoint/CalMS21/checkpoint.pth.tar
evaluate: False
![image](https://user-images.githubusercontent.com/53425563/226091208-df6bc1cc-5de5-401e-9fce-8375c640e733.png)
![image](https://user-images.githubusercontent.com/53425563/226091220-84ece05d-d114-4de3-a193-ac3c70155957.png)
![image](https://user-images.githubusercontent.com/53425563/226091238-0a268fea-609d-43d8-8947-722529a9a7c1.png)

**Comment by jenjsun** [comment]
Hi & thanks for your interest in our project! The current release of our code doesn't support multiple identical agents noted below (as you have 3 black mice in your example (the pre-trained model is on 1 black mouse & 1 white mouse)):

![image](https://user-images.githubusercontent.com/40725770/226215394-29396453-81cb-4663-9cee-6c397522b8f4.png)

We are still working on open-sourcing the version of our code that would address multiple identical agents, but we have an internal version of our code that handles this. If you'd like us to help run the multi-agent version of our code on your videos, feel free to share your videos here! https://forms.gle/k5gwNxws8xMEEzUe6

Otherwise, we can update when the multi-agent version is open-sourced!

**Comment by STAR-811** [comment]
Thank you
